name: Node.js Publish
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: Ubuntu-latest

    strategy:
      matrix:
        package:
          - '@json2csv/formatters'
          - '@json2csv/transforms'
          - '@json2csv/plainjs'
          - '@json2csv/whatwg'
          - '@json2csv/node'
          - '@json2csv/cli'

    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          # Needs to be explicitly specified for auth to work
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public -w ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}